### ISSUE TITLE
Sudden Death tint - Is this Ryan or Amanda?

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#103]
Tint was pretty dreadful. Goes a really shitty red colour and then gets redder as time progresses. It just looks annoying. I like the idea of having it gradually get darker so it's harder but a colour other than that Uluru-red colour would work best me-thinks. Alternatively have no tint at all. No need to washout all of the pretty art.

**Comment by Quaggles** [comment]
You can tweak the sudden death color on the Settings gameobject in the Debug scene
