### ISSUE TITLE
23: Players can't die if they don't have a weapon.

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#104]
So at the end of sudden death the rocks and the hits into the sun had GROWN Sisyphus' health bar instead of shrinking it. It ended up about 3 inches long yet all red.

Taking Damage also does not deplete the glitched health bar.

**Comment by Quaggles** [comment]
Might be fixed with 3ea57f6180cd899aec8da79ca3617df91cdcebdb

Test again please
