### ISSUE TITLE
Mouse and Keyboard Controls

### ISSUE THREAD

**Issue by YaxMan** [Quaggles/Icarus#138]
Add Mouse and Keyboard controls to the game. Also a way that the game can recognise both controls and keyboard inputs, some way that players can easily switch between the two if they like. Also possibly make each action re-bindable.

**Comment by Quaggles** [comment]
Fixed with 89897443af60fdd42add6161065501e4984bc705, f2379263b154453581c76b4530f92819370b54ec and 5eb8667cb1a298d8a89eebb1f3059b40f9846ccf
