### ISSUE TITLE
Implement New Credits

### ISSUE THREAD

**Issue by Quaggles** [Quaggles/Icarus#147]
Information includes:
Team Members
Third party tools that we used
Third Party Assets used (Check to see that we had permission to use them in the first place)
Any additional information

**Comment by YaxMan** [comment]
Done unless I missed anything. Just add in that guy who did the sound effects for us.

**Comment by YaxMan** [comment]
Bump. As I've said it's done. All the credits can be found here. Except for that friend of yours who did the sound effects:

https://drive.google.com/open?id=0B2_7yywpwErUNjhIRHFGQjBNVlE
