### ISSUE TITLE
Arachne's Web has inconsistent power.

### ISSUE THREAD

**Issue by YaxMan** [Quaggles/Icarus#160]
When using Arachne's web the power of the pull will vary. I found it to be about 50% normal power (player that was hit would be immediately in front of Arachne) and 50% high power (player that was hit moves from far in front of Arachne, to far behind Arachne).

This also occurs with all characters using the whip.

Recreatable: Have a game with 2 players, keeping hit a player with Arachne's whip and see the different outcomes.

**Comment by Quaggles** [comment]
Fixed with 39515986b58a47691f80851b96c4cef13e3167f2
