### ISSUE TITLE
Lamia is a ghost on my computer now too!

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#25]
she's a white outline after i built the exe. sad face.

**Comment by YaxMan** [comment]
That's probably my commit that's doing it. It's easily fixable though. Just not on my comp.

**Comment by Quaggles** [comment]
Uh I don't have this problem on my pc? Still happening?

**Comment by mattmelville** [comment]
just synced git to try again and yeah she's still white. also, the AI characters spawned with no weapon icon above their heads

**Comment by Quaggles** [comment]
Hmm must be because I make github not sync the library folder which isn't normally needed. Do you know how to manually assign the materials. You could try deleting and recloning.

**Comment by Quaggles** [comment]
Is this still an issue with anyone or can I close it? @mattmelville @YaxMan
