### ISSUE TITLE
34: AI are Dumb and Attack each other repeatedly.

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#28]
Keep knocking against each other repeatedly. Also does not attempt to fly out of the sun once hit in there.

**Comment by YaxMan** [comment]
All AI do this.

**Comment by Quaggles** [comment]
Can you reproduce this? Do they try and attack dead players or something?

**Comment by mattmelville** [comment]
when it happened, an ai character hit another ai character into the sun and the one who was in the sun just stayed there and didnt bother trying to come out

**Comment by Quaggles** [comment]
Hmm the AI might be trying to target dead players which causes them to continue to run into the sun trying to attack them, will investigate.

**Comment by Quaggles** [comment]
Is this still an issue @YaxMan

**Comment by YaxMan** [comment]
POKE: Yes this is still an issue.

**Comment by Quaggles** [comment]
Fixed 52a66d8e4461b3cbe8aa95dc00cacee4808a9ea7
