### ISSUE TITLE
arachne wins with a body double

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#35]
Game doesn't end when arachne wins and she has a double active. I had to kill my body double and then when it went to the victory screen, a second ixion was on the gold podium but the text said that Arachne won. 

This may also occur with other characters but it just happened with arachne.

**Comment by Quaggles** [comment]
Right, this is because the AI Copy from the God Favour is counted as a real player which stops the game from ending and causes it to show up on the victory screen. Will fix

**Comment by Quaggles** [comment]
Fixed with e9faa3ec1cc4b126a70d651494c64229130d7ded
