### ISSUE TITLE
Double arachne 

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#42]
Two arachnes in game means one or both lose their bodies. This apparently happens for every character however

**Comment by Quaggles** [comment]
This is a really annoying bug related to the way the game flips players when they change direction, I recommend disabling the AI Copy God Favour for upcoming playtests until I can focus on this.

**Comment by Quaggles** [comment]
Fixed now that the menu system doesn't allow duplicate players 893f6e2ff4bd7b96403b94e59489693562eb94d3
