### ISSUE TITLE
menu navigation

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#43]
one button (the A button) should be used all the way through as this is the most natural. Don't use Start, X, etc. it seems too much and is not natural for players
More information about using bumpers to change AI settings and level settings.
use d-pad to navigate menu too, not just joystick

**Comment by Quaggles** [comment]
Will be done when redoing menu system

**Comment by Quaggles** [comment]
Fixed with 893f6e2ff4bd7b96403b94e59489693562eb94d3
