### ISSUE TITLE
Player Tracking

### ISSUE THREAD

**Issue by YaxMan** [Quaggles/Icarus#64]
Add a coloured trim around each players wings to make them more visible.

**Comment by Quaggles** [comment]
Not sure this is possible to implement with the current Puppet2D system we use as the characters aren't sprites or 3D models, more of a mesh (lol) of both. Will investigate

**Comment by MandaJ** [comment]
Might be easier to tint the colour of the wings for each player?

**Comment by Quaggles** [comment]
That can be pretty hard to see when there is a ranged weapon on their back and a lot of action going on
