### ISSUE TITLE
Victory Screen "New Text" Glitch when one player starts game.

### ISSUE THREAD

**Issue by YaxMan** [Quaggles/Icarus#70]
Make Victory Screen say "You lose" or "You fail" when one player enters a game by themselves and dies.

**Comment by Quaggles** [comment]
I tried starting a game by myself and it wouldn't let me so I don't think it's an issue. Can you even start a game by yourself?

**Comment by YaxMan** [comment]
You use to be able to. Before the new menu system so potentially not.
