### ISSUE TITLE
Arachne- Can't animate. 

### ISSUE THREAD

**Issue by Millicentcake** [Quaggles/Icarus#80]
Her global control is telling me she has no stored animations, probably simple fix, but I can't touch her right now

**Comment by Quaggles** [comment]
Works perfectly for me. Selected Global_CTRL, opened animator window, saw animations. If that doesn't work try opening up the Animator (State Machine) and then opening the animation window.

**Comment by Millicentcake** [comment]
Fixed

**Comment by Quaggles** [comment]
If something is fixed click "Close and comment" as the bottom under the text box. This marks the issue as fixed.
