### ISSUE TITLE
22: Players are only Heads and Wings

### ISSUE THREAD

**Issue by mattmelville** [Quaggles/Icarus#88]
AI players were the only ones left so we restarted the game through the menu options however upon restart, EVERYONE had lost their bodies. We restarted 5 times swapping AI in and out and changed characters multiple times yet the missing body bug persisted until we closed the game and then booted it back up again.

**Comment by Quaggles** [comment]
Did you use the restart or quit button on the pause menu?

**Comment by YaxMan** [comment]
Restart on the pause menu.
